### ISSUE TITLE
Adguard Login Issue + Install Script Issue

### ISSUE THREAD

**Issue by ParallaxCoder** [NOXCIS/Wiregate#33]
Hello,

`./install.sh ad-exp` command install pihole instead of adguard. 

if you select adguard using `./install.sh` menu, it install adguard home but gives (express install) a random password or username that doesn't work.

i used your script when it was named worm-hole. it worked perfectly. today I tried to setup this for a friend of mine at got above issues. thanks

**Comment by NOXCIS** [comment]
- should be working now
