### ISSUE TITLE
Automatic server ip detection not working

### ISSUE THREAD

**Issue by Kapyyyy** [NOXCIS/Wiregate#36]
I'm running this on an oracle vps on ubuntu 20.04 Lts and I encountered this issue before while using worm-hole as well, but back then the installer let me set the server ip manually which helped me get it working.

I ran the installer script in both deploy modes, but neither figured out the ip correctly and neither let me set it manually.

**Comment by NOXCIS** [comment]
Not sure why server ip detection isn't working for you, but the wiregate container environment can be preconfigured for your use case check  dev-docker-compose for reference.

**Comment by NOXCIS** [comment]
You can find the origin compose files in Global Configs

**Comment by NOXCIS** [comment]
Or use the preconfigured option and fillout the wiregate.env in global configs

**Comment by Kapyyyy** [comment]
It seems to be grabbing the internal ip instead of the external one.

**Comment by 8beet** [comment]
@NOXCIS i do have the same issue where it auto detects my local IP for the wiregate server but I this fix works easily enough.

**Comment by NOXCIS** [comment]
Ill re-add the manual set for server IP in the Kraken release comming in a few days

**Comment by NOXCIS** [comment]
All the installer really does is allow you to deploy without hardcoded environment variables in the compose.
