### ISSUE TITLE
install_requirements loop and exit installer

### ISSUE THREAD

**Issue by 8beet** [NOXCIS/Wiregate#37]
With the kraken release, when trying to run the install.sh, the install_requirements function loops then the installer exits. I removed the function from the install.sh and installer proceeded ok. It looks like maybe the docker install function is looping despite docker packages being installed. The issue seems to persist regardless of whether basic/advanced and pihole/adguard options selected.

**Comment by NOXCIS** [comment]
Thanks ill take a look at it

**Comment by NOXCIS** [comment]
I'm having trouble replicating your issue Debian and Ubuntu tested VPS.
