### ISSUE TITLE
Install script will exit is swap file already exists

### ISSUE THREAD

**Issue by MohamedElashri** [NOXCIS/Wiregate#39]
If installing `Wiregate` on a Linux machine with already `swapfile` exists it will exit and not continue with installation steps byeond the OS requirmenets. 

It is here in the [code](https://github.com/NOXCIS/Wiregate/blob/0f8419520cba172d6405daccc6cbc6cf0279e122/Core-Installer-Functions/OS-Reqs.sh#L130)

There should be a better way to handle this situation

**Comment by NOXCIS** [comment]
This should fix it [update](https://github.com/NOXCIS/Wiregate/blob/33cb5d603fd512e57a77a0f55e44fc274aefbaf1/Core-Installer-Functions/OS-Reqs.sh#L126)
