### ISSUE TITLE
Custom PreConfigured Install not pulling info from wiregate.env

### ISSUE THREAD

**Issue by BeansIsFat** [NOXCIS/Wiregate#42]
I'm finding a number of obstacles using the Custom PreConfigured Install option.

First, the readme is outdated so I found the correct command from `install.sh`.

Second, running any of the valid options, e.g. `sudo ./install.sh pi-predef-dwire` ignores items in the `Global-Configs/WireGate-Deploy-ENV/wiregate.env` file, like the `WG_DASH_USER` or `WG_DASH_PORT_RANGE_START`.

Third, the resulting install generates a faulty master key, omitting the port for the peer endpoint.

Finally, a related question—what's the best way to keep things updated. Typically I'd run `docker compose pull && docker compose up -d --remove-orphans` however it seems like the substitutions taking place in the docker-compose file mean I need to run the install script again. But will that keep my custom settings and passwords or do I have to enter them each time? That's the main reason I started looking at the preconfigured install, but if there's a better way I'm happy adopt it.

**Comment by NOXCIS** [comment]
Off question? Are you good with R

**Comment by BeansIsFat** [comment]
> @BeansIsFat Off question? Are you good with R

I use R on occasion and can usually get it to do what I want. Not sure that qualifies as "good" but it's good enough for my infrequent needs.

**Comment by NOXCIS** [comment]
Fixed a last week.
