### ISSUE TITLE
Outgoing internet

### ISSUE THREAD

**Issue by amp9020** [NOXCIS/Wiregate#44]
First of all, great work on this stack.

This is more of a question than an issue.

Is it possible to have a wireguard connection (torguard for example) for sending all traffic that goes from the server?

The use case in the github page says, " VPN Splitter - Wiregate can be used to extend the number of clients allowed by any VPN service provider by using your Wiregate machine as a hub".

I couldn't find any other documentation if this is the feature i"m looking for.

If this is the same ask, can someone give me some insight on how I can configure a wireguard connection in this stack?

Thanks in advance,
amp

**Comment by amp9020** [comment]
to be clear, i just want a wireguard connection on outgoing traffic  to be more private

**Comment by NOXCIS** [comment]
@amp9020 How about output to tor network and dns split to cloudflare via DnsCrypt and ODOH? If so check the prion tor branch, its still in devolment.
