### ISSUE TITLE
port forwarding 51820

### ISSUE THREAD

**Issue by LegendarySpy** [NOXCIS/Wiregate#47]
This is more of a question than a issue. In setting up wiregate it works great on LAN but once I try it from a hotspot or other network it just doesn't work. I was under the impression that port 51820 had to be UDP forwarded and that was all. I looked around for quite a bit and I still cant figure it out.

I currently have wiregate running on a fresh install of dietpi on a Pi 4 on ethernet.

**Comment by NOXCIS** [comment]
Send a screenshot of the install output.

**Comment by LegendarySpy** [comment]
After performing a fresh installation of DietPi, I switch to local install mode and select Express, AdGuard, and Dark Wire for installation. If the Raspberry Pi shuts down, is there a way to restore everything without having to rerun the installation script?


<img width="933" alt="image" src="https://github.com/user-attachments/assets/8a6912f0-a5e1-4510-af43-62f008dcdd37">

**Comment by NOXCIS** [comment]
Forward the given port mappings. Wirehole is set to randomize the portmappings if not set manually. Also you can use the environment variables file to set a consistent deployment.

**Comment by LegendarySpy** [comment]
I apologize for the ongoing issue, but it still doesn't seem to be working correctly. I'm using Portainer to monitor all the exposed ports:

![Portainer Ports](https://github.com/user-attachments/assets/98c80c8b-418b-48e7-9f83-f2a31e4baec7)

Based on this, I've port-forwarded all of them to the Raspberry Pi:

![Port Forwarding](https://github.com/user-attachments/assets/8b696eae-f72c-4c27-9d0c-3f513fb230a6)

However, there is still no response. I checked the ports on the Pi using `netstat -lnu`, which shows the UDP ports, but none of them appear to be listening for connections. I'm unsure of what else to try at this point and am starting to suspect this might be a bug that arises when deploying locally.

**Comment by NOXCIS** [comment]
Can you provide a bit more detail about your setup. It seems the masterkey config isn't generation properly. The endpoint doesn't match the given port mappings. I'll do some checks and get back to you this weekend.

**Comment by LegendarySpy** [comment]
Yeah, thanks for the continued help BTW, I'm running WireGate on a RPI 4, I did a fresh install of Dietpi and now using wiregate and portrainer to manage it. Everything for WG works great locally but it just doesn't want to connect outside of LAN with all of the open ports forwarded. The pi itself is ethernet connected.

**Comment by NOXCIS** [comment]
I'll recreate your setup on my local net.

**Comment by NOXCIS** [comment]
@LegendarySpy Found the issue. Update your endpoint IP to your public IP in the master key. Use the install menu to reset the deployment properly. Update perma fix coming this weekend.

**Comment by LegendarySpy** [comment]
Yeah, that worked. Thank you so much for the help this far 👍
