### ISSUE TITLE
Question: Podman support

### ISSUE THREAD

**Issue by alexanderadam** [NOXCIS/Wiregate#52]
Wiregate looks nice.

Does it also run in rootless Podman? Or is this planned?

**Comment by NOXCIS** [comment]
@alexanderadam It seems to work, just make sure to set your port mappings start above 1024. Ill Intigrate podman into the installer later maybe.

**Comment by NOXCIS** [comment]
@alexanderadam How do you keep your sanity using that piece of shit. Sometimes install, sometimes not. I tried to start a podman machine on several machines. It worked once on one RPI5 and refused on another. What your process?

**Comment by alexanderadam** [comment]
I mean, there are different possibilities:

- you could just use the regular run commands (like in Docker)
- you could use [Podman compose](https://docs.podman.io/en/v5.2.2/markdown/podman-compose.1.html) (similar to Docker)
- [you can use system unit files](https://www.redhat.com/sysadmin/podman-run-pods-systemd-services)
- or the new (well, [beginning of last year](https://www.redhat.com/sysadmin/quadlet-podman)) cool way: using Quatlet](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html) files to integrate with systemd (I prefer that nowadays)

And you could combine it with Ansible, OpenTofu, Chef, Puppet, SaltStack, Pulumi, OpenShift and whatnot.

I used Docker in the years before and Podman solved basically all the issues I ever ran into.

However, what do you mean by "sometimes install, sometimes not"?

Like, you can't _install_ podman?
How did you try to install it and what was the error message that you got?

**Comment by NOXCIS** [comment]
@alexanderadam Thanks, I found the culprit![image](https://github.com/user-attachments/assets/aef7702f-fc2e-4a10-811b-60d9f8cf1f30)
