### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by RubiCom001** [NOXCIS/Wiregate#54]
Hi,
I'm not sure, if that is correct, doesn't make much sense. When you set up WireGate (not the did), all seems fine. However, when you go to network config, for example Members, in the PreDown and PostUp , the scripts are from "LAN-only-users", for example:
/opt/wireguarddashboard/src/iptable-rules/LAN-only-users/postdown.sh

If to check the same for LANP2P network, it takes those scripts from "Guest", for example:
/opt/wireguarddashboard/src/iptable-rules/Guest/postdown.sh

For Guests network, scripts are loaded from "Members"

**Comment by NOXCIS** [comment]
@RubiCom001 Thanks for pointing that out. It should be fixed now. 
The reason it still worked was because the interface name is defined in the script, it just so happened to be started by another interface but will still only affect the target interface.

**Comment by RubiCom001** [comment]
Thanks! That was quick :) I've tested it, brand new installation. works fine now.
