### ISSUE TITLE
WGDashboard update

### ISSUE THREAD

**Issue by aleminkirali** [NOXCIS/Wiregate#55]
I'm a big fan of Wiregate! I am using the Docker In Docker install method.  Do you know when the new update for WGDashboard will be available? The new features look really useful for my needs.

**Comment by NOXCIS** [comment]
- @aleminkirali check the AmneziaWG branch it's two days behind the newest WGDashboard v 4.1 because of some functional breaking changes. I.E they are testing ipv6 in the main. 

I also added tor vanguards.

**Comment by NOXCIS** [comment]
@aleminkirali use the dev compose as I haven't update the install stack script yet.

**Comment by NOXCIS** [comment]
godspeed
