### ISSUE TITLE
Both generated password and provided password doesn't work.

### ISSUE THREAD

**Issue by saishwetoe** [NOXCIS/Wiregate#62]
I am accessing the dashboard with Amnezia VPN with a config file which I use the key from the terminal.
The printed password from the terminal doesn't seem to work.
Am I missing something?

**Comment by NOXCIS** [comment]
@saishwetoe Just tested it on a clean system. You might be doing something wrong, run `sudo ./install reset` then install agian. Or just use the docker compose. The installer is a literal crutch.

**Comment by saishwetoe** [comment]
Thanks,

Resetting before reinstalling seem to work.
